export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login/',
    LOGOUT: '/auth/logout/',
    REFRESH: '/auth/token/refresh/',
    ME: '/auth/me/',
  },
  USERS: {
    LIST: '/users/',
    DETAIL: (id: number) => `/users/${id}/`,
  },
  FINANCE: {
    INVOICES: '/finance/invoices/',
    PAYMENTS: '/finance/payments/',
    DASHBOARD: '/finance/dashboard/',
  },
  OPERATIONS: {
    PROJECTS: '/operations/projects/',
    TASKS: '/operations/tasks/',
    DASHBOARD: '/operations/dashboard/',
  },
  COMPLIANCE: {
    AUDITS: '/compliance/audits/',
    RISKS: '/compliance/risks/',
    DASHBOARD: '/compliance/dashboard/',
  },
  HCM: {
    EMPLOYEES: '/hcm/employees/',
    EMPLOYEE_DETAIL: (id: number) => `/hcm/employees/${id}/`,
    DEPARTMENTS: '/hcm/departments/',
    ROLES: '/hcm/roles/',
    LEAVE_REQUESTS: '/hcm/leave-requests/',
    DASHBOARD: '/hcm/dashboard/',
  },
  PROJECTS: {
    LIST: '/projects/',
    DETAIL: (id: number) => `/projects/${id}/`,
    TASKS: '/projects/tasks/',
    TASK_DETAIL: (id: number) => `/projects/tasks/${id}/`,
    MILESTONES: '/projects/milestones/',
    DASHBOARD: '/projects/dashboard/',
  },
  ANALYTICS: {
    EXECUTIVE: '/analytics/executive/',
    KPI: '/analytics/kpi/',
    REPORTS: '/analytics/reports/',
    CHARTS: '/analytics/charts/',
  },
  COMPLIANCE_RISK: {
    FRAMEWORKS: '/compliance-risk/frameworks/',
    FRAMEWORK_DETAIL: (id: number) => `/compliance-risk/frameworks/${id}/`,
    CONTROLS: '/compliance-risk/controls/',
    CONTROL_DETAIL: (id: number) => `/compliance-risk/controls/${id}/`,
    ASSESSMENTS: '/compliance-risk/assessments/',
    ASSESSMENT_DETAIL: (id: number) => `/compliance-risk/assessments/${id}/`,
    RISK_REGISTER: '/compliance-risk/risk-register/',
    RISK_DETAIL: (id: number) => `/compliance-risk/risk-register/${id}/`,
    POLICIES: '/compliance-risk/policies/',
    EVIDENCE: '/compliance-risk/evidence/',
    DASHBOARD: '/compliance-risk/dashboard/',
    GAP_ANALYSIS: '/compliance-risk/gap-analysis/',
  },
  CLIENTS: {
    LIST: '/clients/',
    DETAIL: (id: number) => `/clients/${id}/`,
    CONTACTS: (clientId: number) => `/clients/${clientId}/contacts/`,
    SERVICES: (clientId: number) => `/clients/${clientId}/services/`,
    COMPLIANCE_STATUS: (clientId: number) => `/clients/${clientId}/compliance-status/`,
    DASHBOARD: (clientId: number) => `/clients/${clientId}/dashboard/`,
  },
  ENGAGEMENTS: {
    LIST: '/engagements/',
    DETAIL: (id: number) => `/engagements/${id}/`,
    DELIVERABLES: '/engagements/deliverables/',
    TICKETS: '/engagements/tickets/',
    TICKET_DETAIL: (id: number) => `/engagements/tickets/${id}/`,
    TIME_ENTRIES: '/engagements/time-entries/',
    COMMUNICATIONS: '/engagements/communications/',
  },
  TRAINING: {
    COURSES: '/training/courses/',
    COURSE_DETAIL: (id: number) => `/training/courses/${id}/`,
    ASSIGNMENTS: '/training/assignments/',
    ASSIGNMENT_DETAIL: (id: number) => `/training/assignments/${id}/`,
    PROGRESS: '/training/progress/',
    CERTIFICATES: '/training/certificates/',
    PHISHING_CAMPAIGNS: '/training/phishing-campaigns/',
    CAMPAIGN_DETAIL: (id: number) => `/training/phishing-campaigns/${id}/`,
  },
  DOCUMENTS: {
    LIST: '/documents/',
    DETAIL: (id: number) => `/documents/${id}/`,
    UPLOAD: '/documents/upload/',
    DOWNLOAD: (id: number) => `/documents/${id}/download/`,
    POLICIES: '/documents/policies/',
    PROCEDURES: '/documents/procedures/',
    TEMPLATES: '/documents/templates/',
    VERSIONS: (id: number) => `/documents/${id}/versions/`,
  },
  SOC: {
    INCIDENTS: '/soc/incidents/',
    INCIDENT_DETAIL: (id: number) => `/soc/incidents/${id}/`,
    ALERTS: '/soc/alerts/',
    VULNERABILITIES: '/soc/vulnerabilities/',
    THREAT_INTEL: '/soc/threat-intel/',
    DASHBOARD: '/soc/dashboard/',
    METRICS: '/soc/metrics/',
  },
} as const;
